/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author PACKERDBELL
 */
public class BiletAlma extends javax.swing.JFrame {

                String koltuuuk="";
		int Asayısı = 0;
	        int Bsayısı=0;
                int Csayısı=0;
		int APrice = 0;
                int Bprice=0;
                int Cprice=0;
	         int i=0;
                 int k=0;
                 int l=0;
                 int m=0;
                 
		int toplam = 0; 
    /**
     * Creates new form BiletAlma
     */
    public BiletAlma() {
        initComponents();
        koltuk_kontrol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void koltuk_kontrol()
{
    String seanss=(String)FilmSecme.jComboBox2.getSelectedItem();
    String sallon=(String)FilmSecme.jComboBox3.getSelectedItem();

 Connection con =MyConnection.getConnection();
       try{
           Statement st1,st2,st3= null;
         
           ResultSet rs1,rs2,rs3=null;
            st1 = con.createStatement();
            st2 = con.createStatement();
            st3 = con.createStatement();
           
rs1=st1.executeQuery("select * from bilet where koltuk='A1' and salon='"+sallon+"' and seans='"+seanss+"' ");

            rs1.last();
            
            
            
            int kayitsayisi = rs1.getRow();
               
            if(kayitsayisi > 0 ){                       
                btn_1.setText("DOLU");
                btn_1.setEnabled(false);
            }
            else {
                btn_1.setText("A1");
                btn_1.setBackground(Color.GREEN);
            }
           
            rs2 = st2.executeQuery("select * from bilet where koltuk='A2' and salon='"+sallon+"' and seans='"+seanss+"'");
            rs2.last();
            int kayitsayisi2 = rs2.getRow();            
            if(kayitsayisi2 > 0){                
               btn_2.setText("DOLU");
               btn_2.setEnabled(false);
            }
            else {
                btn_2.setText("A2");
                btn_2.setBackground(Color.GREEN);
            }
                
            
            rs3 = st3.executeQuery("select * from bilet where koltuk='A3' and salon='"+sallon+"' and seans='"+seanss+"'");
            rs3.last();
            int kayitsayisi3 = rs3.getRow();            
            if(kayitsayisi3 > 0){                
                btn_3.setText("DOLU");
                btn_3.setEnabled(false);             
            }
            else {
                btn_3.setText("A3");
                btn_3.setBackground(Color.GREEN);
            }
   
       }catch (SQLException ex) {
        Logger.getLogger(Film.class.getName()).log(Level.SEVERE, null, ex);
    }         

}
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        koltuk = new javax.swing.JLabel();
        gonder = new javax.swing.JButton();
        salonadı = new javax.swing.JLabel();
        seansadı = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gonder.setText("Gönder");
        gonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gonderActionPerformed(evt);
            }
        });

        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_1.setFont(new java.awt.Font("Tekton Pro", 3, 18)); // NOI18N
        btn_1.setText("A1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setFont(new java.awt.Font("Tekton Pro", 3, 18)); // NOI18N
        btn_2.setText("A2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setFont(new java.awt.Font("Tekton Pro", 3, 18)); // NOI18N
        btn_3.setText("A3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(248, 248, 248)
                            .addComponent(salonadı, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(109, 109, 109)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(koltuk, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(89, 89, 89))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(seansadı, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(169, 169, 169)
                            .addComponent(gonder, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(koltuk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton1)
                                            .addGap(2, 2, 2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)))
                                    .addComponent(gonder, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(salonadı, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seansadı, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)))
                    .addGap(175, 175, 175)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gonderActionPerformed
   String seanss=(String)FilmSecme.jComboBox2.getSelectedItem();
    String sallon=(String)FilmSecme.jComboBox3.getSelectedItem();
        String koltukk=koltuk.getText();
        String[] koll = koltukk.split(" ");
        koltuk_kontrol();
        try{
            if(koltuk.equals("")){
                JOptionPane.showMessageDialog(this, "Lütfen Koltuk Seçiniz!");
            }
            else {
                for(int j=0; j<i; j++){
                    Connection con =MyConnection.getConnection();
                    Statement st = con.createStatement();
                    String sql = "INSERT INTO bilet (salon,seans,koltuk)"
                    + " VALUES ('"+sallon+"','"+seanss+"','"+koll[j]+"')";

                    st.executeUpdate(sql); }
                JOptionPane.showMessageDialog(null, " İşleminiz Gerçekleşmiştir. İyi Yolculuklar.");

            }

        } catch (SQLException ex) {
            Logger.getLogger(Film.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_gonderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // koltuk_kontrol();
        try{
            koltuk_kontrol();
            koltuuuk="";

            koltuk.setText(koltuuuk);
            i=0;
            if(btn_1.getBackground()==Color.red )
            { btn_1.setBackground(Color.green);
            }
            if(btn_2.getBackground()==Color.red)
            { btn_2.setBackground(Color.green);
            }
            if(btn_3.getBackground()==Color.red)
            { btn_3.setBackground(Color.green);
            }
            k=0;
            l=0;
            m=0;
        }

        catch (Exception ex)
        {   JOptionPane.showMessageDialog(null, "HATA"); }

        //                        int price1 = 15;
        //			int price2 = 20;
        //			int price3 = 25;
        //			//CPrice = Csayısı*price1;
        //
        //			APrice = Asayısı*price2;
        //                       // BPrice =  Bsayısı *price2;
        //                       toplam=APrice;
        //                       String ücret = Integer.toString(toplam);
        //
        //       price.setText(ücret);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed

    String seanss=(String)FilmSecme.jComboBox2.getSelectedItem();
    String sallon=(String)FilmSecme.jComboBox3.getSelectedItem();

        try{
            Connection con =MyConnection.getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("select * from bilet where koltuk='A1' and salon='"+sallon+"' and seans='"+seanss+"'");

            int kayitsayisi = rs.getRow();

            if(kayitsayisi > 0){
                JOptionPane.showMessageDialog(null, "Seçtiğiniz Koltuk Doludur!");

            }
            else {
                m++;
                if(m==1){
                    koltuuuk+="A1 ";
                    koltuk.setText(koltuuuk);
                    btn_1.setBackground(Color.red);
                    // btn_3.setEnabled(false);
                    i++;
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Film.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
     String seanss=(String)FilmSecme.jComboBox2.getSelectedItem();
    String sallon=(String)FilmSecme.jComboBox3.getSelectedItem();
        try{
            Connection con =MyConnection.getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("select * from bilet where koltuk='A2' and salon='"+sallon+"' and seans='"+seanss+"'");

            int kayitsayisi = rs.getRow();

            if(kayitsayisi > 0){
                JOptionPane.showMessageDialog(null, "Seçtiğiniz Koltuk Doludur!");
            }
            else {
                l++;
                if(l==1){
                    koltuuuk+="A2 ";
                    koltuk.setText(koltuuuk);
                    btn_2.setBackground(Color.red);
                    // btn_3.setEnabled(false);
                    i++; }

            }

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
   String seanss=(String)FilmSecme.jComboBox2.getSelectedItem();
    String sallon=(String)FilmSecme.jComboBox3.getSelectedItem();
        try{
            Connection con =MyConnection.getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("select * from bilet where koltuk='A3' and salon='"+sallon+"' and seans='"+seanss+"'");

            int kayitsayisi = rs.getRow();

            if(kayitsayisi > 0){
                JOptionPane.showMessageDialog(null, "Seçtiğiniz Koltuk Doludur!");
            }
            else {
                k++;
                if(k==1){
                    koltuuuk+="A3 ";
                    koltuk.setText(koltuuuk);
                    btn_3.setBackground(Color.red);
                    // btn_3.setEnabled(false);
                    i++; }

            }

        } catch (Exception ex) {
            if(k>1){
                JOptionPane.showMessageDialog(null, "Birden fazla koltuğa basmayın..");
            }
        }
    }//GEN-LAST:event_btn_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiletAlma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiletAlma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiletAlma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiletAlma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiletAlma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton gonder;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel koltuk;
    private javax.swing.JLabel price;
    private javax.swing.JLabel salonadı;
    private javax.swing.JLabel seansadı;
    // End of variables declaration//GEN-END:variables
}
